# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tnt_deploy_person.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/tnt_deploy_person.proto',
  package='tnt_deploy',
  serialized_pb='\n\x1dproto/tnt_deploy_person.proto\x12\ntnt_deploy\"\x9d\x01\n\x06PERSON\x12\r\n\x02id\x18\x01 \x02(\r:\x01\x30\x12\x12\n\x08username\x18\x02 \x02(\t:\x00\x12\x0e\n\x03\x61ge\x18\x03 \x01(\r:\x01\x30\x12+\n\tgrade_arr\x18\x04 \x03(\x0b\x32\x18.tnt_deploy.PERSON.grade\x1a\x33\n\x05grade\x12\x13\n\tgradename\x18\x01 \x01(\t:\x00\x12\x15\n\nstart_year\x18\x02 \x01(\r:\x01\x30\"1\n\x0cPERSON_ARRAY\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.tnt_deploy.PERSON')




_PERSON_GRADE = _descriptor.Descriptor(
  name='grade',
  full_name='tnt_deploy.PERSON.grade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gradename', full_name='tnt_deploy.PERSON.grade.gradename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_year', full_name='tnt_deploy.PERSON.grade.start_year', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=203,
)

_PERSON = _descriptor.Descriptor(
  name='PERSON',
  full_name='tnt_deploy.PERSON',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tnt_deploy.PERSON.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='tnt_deploy.PERSON.username', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='tnt_deploy.PERSON.age', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade_arr', full_name='tnt_deploy.PERSON.grade_arr', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_GRADE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=203,
)


_PERSON_ARRAY = _descriptor.Descriptor(
  name='PERSON_ARRAY',
  full_name='tnt_deploy.PERSON_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='tnt_deploy.PERSON_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=205,
  serialized_end=254,
)

_PERSON_GRADE.containing_type = _PERSON;
_PERSON.fields_by_name['grade_arr'].message_type = _PERSON_GRADE
_PERSON_ARRAY.fields_by_name['items'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['PERSON'] = _PERSON
DESCRIPTOR.message_types_by_name['PERSON_ARRAY'] = _PERSON_ARRAY

class PERSON(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class grade(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PERSON_GRADE

    # @@protoc_insertion_point(class_scope:tnt_deploy.PERSON.grade)
  DESCRIPTOR = _PERSON

  # @@protoc_insertion_point(class_scope:tnt_deploy.PERSON)

class PERSON_ARRAY(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERSON_ARRAY

  # @@protoc_insertion_point(class_scope:tnt_deploy.PERSON_ARRAY)


# @@protoc_insertion_point(module_scope)
